### PR TITLE
added support for swedish

### PR DESCRIPTION
**Pull request by Miya25**
# Description

## Type of change

Please delete options that are not relevant.
- [ yes] New feature (non-breaking change which adds functionality)
expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [yes] Test A
- [yes] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [y] My code follows the style guidelines of this project
- [y] I have performed a self-review of my own code
- [y] I have commented my code, particularly in hard-to-understand areas
- [y] I have made corresponding changes to the documentation
- [y] My changes generate no new warnings
- [y] I have added tests that prove my fix is effective or that my feature works
- [y] New and existing unit tests pass locally with my changes
- [y] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by selectthegang** [comment]
lowkey hate that Vercel won't let me authorize this preview deployment

**Review by TheRealToxicDev — APPROVED** [review]
LGTM

**Comment by TheRealToxicDev** [comment]
Hmm

**Review by TheRealToxicDev — APPROVED** [review]
LGTM yes

**Pull request merged**
